{% set version = "4.4.1" %}
{% set hash = "7a9c44400ee0f3b4546066e0710e1250fd75831adc02ab99dda176ad8726f424" %}
{% set pkgname = "coverage" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - toolchain
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Code coverage measurement for Python'

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
